[[polymake]]
arch = "aarch64"
git-tree-sha1 = "bc36a571fbfa824e425db126ea720ab7aac92de0"
os = "macos"

    [[polymake.download]]
    sha256 = "346c97980fac3c3ee02da34721219e3bc31c81eae105363eef3aaeb8818b7407"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.aarch64-apple-darwin.tar.gz"
[[polymake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ccaee23067dbdee783fccb250b7dde8fa09eafe"
libc = "glibc"
os = "linux"

    [[polymake.download]]
    sha256 = "2f04b14a9e7d091907899a17f34599f66382011fb016c475932991312d84ac5f"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.aarch64-linux-gnu-cxx11.tar.gz"
[[polymake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "662d1424986d058f50b7679fcda0450a7a9fe640"
libc = "musl"
os = "linux"

    [[polymake.download]]
    sha256 = "661ddc012991d0430901d54a9ea5078e40a0fa2bfdfed0bed7da784887824b3a"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.aarch64-linux-musl-cxx11.tar.gz"
[[polymake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd4f892f8aae89fe104e338b68afe27b35afba78"
libc = "glibc"
os = "linux"

    [[polymake.download]]
    sha256 = "d80b347fe7df1f39e3c99bb97d70a7de814f10a48109c2e28bb0ad79449d8f72"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[polymake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "624f58b966c61f67cda7f0efafd078d169bf6f58"
libc = "musl"
os = "linux"

    [[polymake.download]]
    sha256 = "b03a426dcfab25fbd1a9205a6c7b18a9798d2efd3ba26b004cf2108957cc601c"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[polymake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d93b580a8f015609d550f4886ea6e75a72ccdde5"
libc = "glibc"
os = "linux"

    [[polymake.download]]
    sha256 = "df191a3ad0e56e846f36d69892fef84067c4060124e4cc17a19c54618b57e6e7"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.i686-linux-gnu-cxx11.tar.gz"
[[polymake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3ef747c7d5752fa8eacddc2bc03779939376cc6"
libc = "musl"
os = "linux"

    [[polymake.download]]
    sha256 = "e685c0389641777a66cf246e9dcb9a8dbfe8d9a089804af64934ebad73fcd3d5"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.i686-linux-musl-cxx11.tar.gz"
[[polymake]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea5978e31e9dbb203c9b4af457bf76de43f1e67c"
libc = "glibc"
os = "linux"

    [[polymake.download]]
    sha256 = "976eb28a81699c8050d908947f90d53e9028a982ba26da452e77e0c5fea8310c"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[polymake]]
arch = "x86_64"
git-tree-sha1 = "28352ae99a17d3aba9bd60f42b11a6b8ee71a091"
os = "macos"

    [[polymake.download]]
    sha256 = "85d04695700f104728df287f007401327be371dc5103d855354ce222e4c2b63e"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.x86_64-apple-darwin.tar.gz"
[[polymake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "791456f09d10ab18096c3ca8461e751ed52102c2"
libc = "glibc"
os = "linux"

    [[polymake.download]]
    sha256 = "37ec535f8ec7069feb46d5939c4799ad846a4212988bca9ae49b7b5a6593b8df"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.x86_64-linux-gnu-cxx11.tar.gz"
[[polymake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1dea17c3cb58d7f7ad21eefdd0e0baffadf056c"
libc = "musl"
os = "linux"

    [[polymake.download]]
    sha256 = "99eadc1959e34a6aafb2d189cb5cb68ccced4e289b7c0c4c93587db3867787e8"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.x86_64-linux-musl-cxx11.tar.gz"
[[polymake]]
arch = "x86_64"
git-tree-sha1 = "1545e87fec4ae2db2d4e9f35a2535407cba08026"
os = "freebsd"

    [[polymake.download]]
    sha256 = "d88e29778d03c4203e609c5a0649cb5529a96d18e9da24f0a08bf9729b9e2cb5"
    url = "https://github.com/JuliaBinaryWrappers/polymake_jll.jl/releases/download/polymake-v400.1500.1+0/polymake.v400.1500.1.x86_64-unknown-freebsd.tar.gz"
